// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: cargo test generate_bindings -- --ignored
// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: cargo test generate_bindings -- --ignored

// This file has been generated by Specta. DO NOT EDIT.

/**
 * Bank account types
 */
export type AccountType = "checking" | "savings" | "credit_card" | "investment"

/**
 * One dated estimate of an asset's value.
 */
export type AssetValuation = { id: string; 
/**
 * `real_estate.id` or `other_assets.id`, depending on the table.
 */
assetId: string; 
/**
 * Market price of the whole property, or price per unit of an other asset (money TEXT).
 */
value: string; currency: string; 
/**
 * UTC day the estimate applies to (ADR 0008).
 */
valuedAt: number; note: string | null; createdAt: number }

/**
 * One file inside a backup archive.
 */
export type BackupFileEntry = { path: string; bytes: number }

/**
 * What the UI shows before asking the user to confirm a restore.
 */
export type BackupInspection = { manifest: BackupManifest; archivePath: string; archiveBytes: number; attachmentCount: number; 
/**
 * The archive's database was migrated by a newer Moony than this build.
 */
newerThanApp: boolean }

/**
 * `manifest.json` written into every backup archive.
 */
export type BackupManifest = { format: number; appVersion: string; createdAt: number; 
/**
 * Names of the migrations applied to the database inside the archive.
 */
migrations: string[]; files: BackupFileEntry[] }

/**
 * Bank account entity
 */
export type BankAccount = { id: string; name: string; accountType: string; iban: string | null; bban: string | null; currency: string; balance: string; institutionId: string | null; externalAccountId: string | null; dataSource: string; lastSyncedAt: number | null; interestRate: string | null; hasZoneDesignation: boolean; terminationDate: number | null; 
/**
 * Left out of net worth, totals and charts when true (still listed and editable).
 */
excludeFromBalance: boolean; createdAt: number; updatedAt: number }

/**
 * Bank account with institution data (enriched)
 */
export type BankAccountWithInstitution = ({ id: string; name: string; accountType: string; iban: string | null; bban: string | null; currency: string; balance: string; institutionId: string | null; externalAccountId: string | null; dataSource: string; lastSyncedAt: number | null; interestRate: string | null; hasZoneDesignation: boolean; terminationDate: number | null; 
/**
 * Left out of net worth, totals and charts when true (still listed and editable).
 */
excludeFromBalance: boolean; createdAt: number; updatedAt: number }) & { institution: Institution | null; effectiveInterestRate: number | null; projectedEarnings: number | null }

/**
 * Bank transaction entity
 */
export type BankTransaction = { id: string; bankAccountId: string; transactionId: string | null; type: string; amount: string; currency: string; description: string | null; counterpartyName: string | null; counterpartyIban: string | null; bookingDate: number; valueDate: number | null; categoryId: string | null; merchantCategoryCode: string | null; remittanceInfo: string | null; 
/**
 * Category suggested by an MCP client, pending user confirmation
 */
suggestedCategoryId: string | null; status: string; dataSource: string; createdAt: number }

/**
 * Bond holding
 */
export type Bond = { id: string; name: string; isin: string | null; couponValue: string; quantity: string; currency: string; interestRate: string; maturityDate: number | null; createdAt: number; updatedAt: number }

/**
 * Actual monthly cashflow for a range plus the preceding range of equal length.
 */
export type CashflowActuals = { 
/**
 * `6m`, `12m` or `ytd`.
 */
range: string; rangeStart: number; rangeEnd: number; previousStart: number; previousEnd: number; 
/**
 * Every month of the range, oldest first, zero-filled.
 */
months: CashflowMonth[]; 
/**
 * Net expenses by category, largest first (refunds reduce a category).
 */
expenseCategories: CashflowGroup[]; 
/**
 * Income by counterparty, largest first.
 */
incomeSources: CashflowGroup[]; totalIncome: string; totalExpenses: string; previousIncome: string; previousExpenses: string; 
/**
 * Bank accounts that had a transaction in the range.
 */
accountCount: number; 
/**
 * Transactions counted in the range (internal transfers excluded).
 */
transactionCount: number }

/**
 * One row of "expenses by category" or "income by source", with the same sum
 * for the preceding range so the UI can show "vs. minulé".
 */
export type CashflowGroup = { 
/**
 * Category id (`uncategorized` for rows without one) or a normalized source key.
 */
key: string; 
/**
 * Category name as stored, or the counterparty as first seen; empty for an unknown source.
 */
name: string; amount: string; previousAmount: string; 
/**
 * Transactions behind `amount` in the current range.
 */
count: number }

/**
 * User-defined cashflow item (income or expense)
 */
export type CashflowItem = { id: string; name: string; amount: string; currency: string; frequency: string; itemType: string; category: string; createdAt: number; updatedAt: number }

/**
 * Income and expenses of one calendar month (UTC).
 */
export type CashflowMonth = { 
/**
 * Unix seconds of the first day of the month, UTC midnight.
 */
month: number; income: string; expenses: string }

/**
 * The automation rate (TS `CategorizationOverview`).
 */
export type CategorizationOverview = { total: number; categorized: number; bySource: SourceCount[] }

/**
 * How many rows reference a category — what a delete would have to move.
 */
export type CategoryUsage = { categoryId: string; transactions: number; rules: number; learnedPayees: number; budgetGoals: number }

/**
 * Crypto investment holding
 */
export type CryptoInvestment = { id: string; ticker: string; coingeckoId: string; name: string; quantity: string; averagePrice: string }

/**
 * Crypto transaction (buy/sell)
 */
export type CryptoTransaction = { id: string; investmentId: string; type: string; ticker: string; name: string; quantity: string; pricePerUnit: string; currency: string; transactionDate: number; createdAt: number }

/**
 * One row's category chosen in the preview (TS `CsvCategoryOverride`).
 */
export type CsvCategoryOverride = { 
/**
 * 1-based file line of the row.
 */
line: number; categoryId: string }

/**
 * Inclusive range of booking dates (unix seconds, midnight UTC).
 */
export type CsvDateRange = { from: number; to: number }

/**
 * Configuration of one CSV import or preview (TS `CsvImportConfigInput`).
 * 
 * Column names are the file's header cells; a name that differs only in case,
 * diacritics or punctuation still resolves (see `columns::find_column`), so a
 * preset's spelling can be passed through unchanged.
 */
export type CsvImportConfig = { 
/**
 * One character; empty = auto-detect.
 */
delimiter: string; 
/**
 * Data rows to skip *after* the header row.
 */
skipRows?: number; 
/**
 * 0-based line of the header row; `None` = auto-detect.
 */
headerRow?: number | null; dateColumn: string; 
/**
 * chrono format (`%d.%m.%Y`). Parsed strictly: a row that does not match
 * is an error, never re-read as another order. Empty or `auto` detects the
 * format from the date column.
 */
dateFormat: string; 
/**
 * Single signed amount column. Optional when a debit/credit pair is given.
 */
amountColumn?: string | null; 
/**
 * Debit/credit pair (`amount = credit − debit`). Used when `amountColumn`
 * is not set; both must be set.
 */
debitColumn?: string | null; creditColumn?: string | null; 
/**
 * Running balance after each row; only feeds `lastBalance`.
 */
balanceColumn?: string | null; 
/**
 * Bank-side transaction id; feeds the id rule of the duplicate check.
 */
transactionIdColumn?: string | null; descriptionColumns?: string[] | null; counterpartyColumn?: string | null; counterpartyIbanColumn?: string | null; currencyColumn?: string | null; 
/**
 * `","` or `"."`; `None`, empty or `auto` detects it from the amount
 * column(s).
 */
decimalSeparator?: string | null; rowFilter?: CsvRowFilter | null; 
/**
 * Skip rows that the duplicate check matches (default). `false` imports
 * them and reports them in `duplicates`.
 */
skipDuplicates?: boolean; 
/**
 * File lines of duplicate rows to import anyway.
 */
importAnywayLines?: number[]; 
/**
 * Force a text encoding (`Windows-1250`); `None` = detect.
 */
encoding?: string | null; 
/**
 * Categories the user picked in the preview for rows the rules left
 * uncategorized (or wanted differently), by file line. Applied on import
 * before the rules run, so they win; a missing category is ignored.
 */
categoryOverrides?: CsvCategoryOverride[] }

/**
 * Dry run of an import (TS `CsvImportPreview`).
 */
export type CsvImportPreview = { 
/**
 * The first 200 rows in file order.
 */
rows: CsvPreviewRow[]; totalRows: number; okCount: number; errorCount: number; duplicateCount: number; 
/**
 * Zero-amount and filtered rows.
 */
skippedCount: number; 
/**
 * Booking dates of the rows an import with this config would write.
 */
dateRange: CsvDateRange | null; 
/**
 * Rows that would be written with a category (rules or overrides).
 */
categorizedCount: number }

/**
 * Result of an import (TS `CsvImportResult`).
 * 
 * Every row of the file ends up in exactly one bucket:
 * `importedCount + skippedDuplicates.len() + errorCount + skippedZero +
 * skippedFiltered` = data rows (blank lines are not rows).
 */
export type CsvImportResult = { 
/**
 * Rows written (includes duplicates that were imported anyway).
 */
importedCount: number; 
/**
 * Duplicate hits that were imported anyway — `duplicates.len()`.
 */
duplicateCount: number; errorCount: number; errors: CsvRowMessage[]; 
/**
 * Duplicates that were imported anyway (`importAnywayLines` or
 * `skipDuplicates: false`).
 */
duplicates: CsvRowMessage[]; 
/**
 * Duplicates that were skipped.
 */
skippedDuplicates: CsvRowMessage[]; skippedZero: number; 
/**
 * Rows dropped by the row filter (Revolut pending rows).
 */
skippedFiltered: number; 
/**
 * Booking dates of the imported rows; `None` when nothing was imported.
 */
dateRange: CsvDateRange | null; 
/**
 * Imported rows the rules could not categorize.
 */
uncategorizedCount: number; 
/**
 * Balance after the chronologically last statement row, as a signed
 * decimal string; `None` without a balance column.
 */
lastBalance: string | null; 
/**
 * Rule-pack id (lowercase ISO country) the counterparty IBANs point to
 * when that pack is not enabled yet.
 */
suggestedRulePack: string | null }

/**
 * One bank's CSV format (wire type — TS `CsvPreset`). `schemaVersion: 1`.
 * 
 * Exactly one of `amountColumn` or the `debitColumn` + `creditColumn` pair is
 * set. Optional text fields are `null` on the wire when absent.
 */
export type CsvPreset = { schemaVersion: number; 
/**
 * Stable kebab-case id, also the file name (`revolut` → `revolut.json`).
 */
id: string; bankName: string; 
/**
 * ISO 3166-1 alpha-2 country of the bank (the UI groups/sorts by it).
 */
country: string; 
/**
 * Row id in the `institutions` table, when the bank is seeded there
 * (lets the dialog preselect the preset from the account's institution).
 */
institutionId?: string | null; 
/**
 * Header cells that must all be present for auto-detection.
 */
matchHeaders: string[]; 
/**
 * One character: `,` `;` or a tab (`"\t"`).
 */
delimiter: string; 
/**
 * Encoding label (`UTF-8`, `Windows-1250`, …). Only consulted when the
 * file is not valid UTF-8 — see `decode_csv_content`.
 */
encoding: string; dateColumn: string; 
/**
 * chrono format of the date column (`%d.%m.%Y`, `%Y-%m-%d %H:%M:%S`).
 */
dateFormat: string; amountColumn?: string | null; debitColumn?: string | null; creditColumn?: string | null; 
/**
 * Joined with " | " in this order into the transaction description.
 */
descriptionColumns: string[]; counterpartyColumn?: string | null; counterpartyIbanColumn?: string | null; currencyColumn?: string | null; balanceColumn?: string | null; 
/**
 * A column that is unique per transaction at the bank (Fio "ID operace");
 * feeds the bank-side-id duplicate rule.
 */
transactionIdColumn?: string | null; rowFilter?: CsvRowFilter | null; exportHelpUrl?: string | null; 
/**
 * File name in `src-tauri/tests/fixtures/csv/` that this
 * preset must import without errors (checked by `all_presets_are_valid`).
 */
sampleFixture?: string | null }

/**
 * What `parse_csv_file` learned about a file (TS `CsvPreviewResult`).
 */
export type CsvPreviewResult = { headers: string[]; 
/**
 * First five data rows.
 */
sampleRows: string[][]; totalRows: number; delimiter: string; 
/**
 * Role → (header, confidence 0–1). Roles: `date`, `valueDate`, `amount`,
 * `debit`, `credit`, `balance`, `currency`, `description`,
 * `counterparty`, `counterparty_iban` (legacy snake_case key),
 * `transactionId`. A detected preset's columns come first, at 1.0.
 */
suggestedMappings: Partial<{ [key in string]: [string, number] }>; 
/**
 * 0-based line of the header row.
 */
headerRow: number; detectedPresetId: string | null; 
/**
 * chrono format of the date column (date part only).
 */
dateFormat: string; 
/**
 * `true` when day/month order cannot be told from the samples (all values
 * ≤ 12 in both positions) and `dateFormat` is a guess the user should
 * confirm.
 */
dateFormatAmbiguous: boolean; 
/**
 * `","` or `"."`.
 */
decimalSeparator: string; 
/**
 * Encoding the file was decoded with.
 */
encoding: string; 
/**
 * All description columns to pre-select: the preset's, else the single
 * suggested `description`.
 */
suggestedDescriptionColumns: string[]; 
/**
 * The detected preset's row filter, resolved to the file's header name.
 */
suggestedRowFilter: CsvRowFilter | null }

/**
 * One row of the preview table.
 */
export type CsvPreviewRow = { line: number; bookingDate: number | null; 
/**
 * Signed decimal string (`-250.5`), `None` when the amount is unreadable.
 */
amount: string | null; currency: string | null; description: string | null; counterparty: string | null; status: CsvRowStatus; message: CsvRowMessage | null; 
/**
 * Category the import would write: the user's override for this line, else
 * what the deterministic rules resolve; `None` = stays uncategorized.
 */
categoryId: string | null; 
/**
 * `manual` for an override, else the rule layer (`rule`, `exact_match`,
 * `own_account`).
 */
categorySource: string | null }

/**
 * Keep only rows whose `column` equals `equals` (case- and whitespace-
 * insensitive). Revolut: `State == COMPLETED` drops PENDING/REVERTED rows.
 */
export type CsvRowFilter = { column: string; equals: string }

/**
 * A per-row problem or note. Never carries English prose: `key` is an i18n
 * key and `detail` the raw value it is about (the unparseable date, the
 * filtered state, …).
 * 
 * Keys (namespace in front of the dot):
 * - `csvImport.*` — `bank_accounts` namespace: `rowCannotParse`,
 * `dateUnparseable`, `amountUnparseable`, `zeroAmount`, `filteredOut`,
 * `duplicate`, `duplicateById`;
 * - `validation.*` — `common` namespace: whatever `InsertBankTransaction::
 * validate()` rejects with (`validation.currencyInvalid`, …),
 * `validation.currencyUnknown` for a currency cell that is not an ISO 4217
 * code (the cell goes in `detail`), plus `validation.dateRequired` /
 * `validation.amountRequired` for empty cells.
 */
export type CsvRowMessage = { 
/**
 * 1-based line of the file where the row starts (the header line counts).
 */
line: number; key: string; detail: string | null }

export type CsvRowStatus = 
/**
 * Will be imported.
 */
"ok" | 
/**
 * Cannot be imported (see `message`).
 */
"error" | 
/**
 * Matches an existing or earlier transaction; skipped unless imported anyway.
 */
"duplicate" | 
/**
 * Dropped on purpose: zero amount or row filter.
 */
"skipped"

/**
 * Where the data lives on this machine.
 */
export type DataLocation = { dataDir: string; dbPath: string; totalBytes: number }

/**
 * Data source for accounts and transactions
 */
export type DataSource = "manual" | "csv_import" | "api_sync"

/**
 * User dividend override
 */
export type DividendOverride = { id: string; ticker: string; yearlyDividendSum: string; currency: string; updatedAt: number }

/**
 * Enriched crypto with current price
 */
export type EnrichedCryptoInvestment = { id: string; ticker: string; coingeckoId: string; name: string; quantity: string; averagePrice: string; 
/**
 * Currency of the average price (native currency from first transaction)
 */
averagePriceCurrency: string; currentPrice: string; 
/**
 * Original price in its source currency (before conversion to CZK)
 */
originalPrice: string; 
/**
 * Currency of the current market price (e.g., USD, EUR)
 */
currency: string; fetchedAt: number | null; 
/**
 * Whether the price is manually overridden
 */
isManualPrice: boolean }

/**
 * Enriched investment with current price data
 */
export type EnrichedStockInvestment = { id: string; ticker: string; companyName: string; quantity: string; averagePrice: string; 
/**
 * Currency of the average price (determined by first transaction)
 */
averagePriceCurrency: string; currentPrice: number; 
/**
 * Original price in its source currency (before conversion to CZK)
 */
originalPrice: string; 
/**
 * Currency of the current price (e.g., USD, EUR)
 */
currency: string; fetchedAt: number | null; isManualPrice: boolean; dividendYield: number; 
/**
 * Original dividend amount before conversion
 */
originalDividendYield: number; dividendCurrency: string; isManualDividend: boolean }

/**
 * Summary of a full JSON export.
 */
export type ExportSummary = { path: string; tableCount: number; rowCount: number }

/**
 * Payload of the `history-recalculation` event.
 */
export type HistoryRecalcEvent = { ticker: string; status: RecalcStatus }

/**
 * Data for recording a valuation.
 */
export type InsertAssetValuation = { assetId: string; value: string; currency: string | null; valuedAt: number; note: string | null }

/**
 * Data for creating/updating a bank account
 */
export type InsertBankAccount = { name: string; accountType: string | null; iban: string | null; bban: string | null; currency: string | null; balance: string | null; institutionId: string | null; interestRate: string | null; hasZoneDesignation: boolean | null; terminationDate: number | null; 
/**
 * `None` keeps the stored value on update and means "included" on create.
 */
excludeFromBalance?: boolean | null }

/**
 * Data for creating/updating a transaction
 */
export type InsertBankTransaction = { bankAccountId: string; transactionId: string | null; type: string; amount: string; currency: string | null; description: string | null; counterpartyName: string | null; counterpartyIban: string | null; bookingDate: number; valueDate: number | null; categoryId: string | null; status: string | null }

/**
 * Data for creating/updating bond
 */
export type InsertBond = { name: string; isin: string | null; couponValue: string; quantity: string | null; currency: string | null; interestRate: string | null; maturityDate: number | null }

/**
 * Data for creating/updating cashflow item
 */
export type InsertCashflowItem = { name: string; amount: string; currency: string | null; frequency: string; itemType: string; category: string }

/**
 * Data for creating crypto investment. Quantity and average price are not
 * accepted: they derive from the transaction record (pass an initial
 * transaction on create).
 */
export type InsertCryptoInvestment = { ticker: string; coingeckoId: string; name: string }

/**
 * Data for creating crypto transaction
 */
export type InsertCryptoTransaction = { investmentId: string | null; type: string; ticker: string; name: string; quantity: string; pricePerUnit: string; currency: string; transactionDate: number }

/**
 * Data for creating/updating insurance policy
 */
export type InsertInsurancePolicy = { type: string; provider: string; policyName: string; policyNumber: string | null; startDate: number; endDate: number | null; paymentFrequency: string; oneTimePayment: string | null; oneTimePaymentCurrency: string | null; regularPayment: string | null; regularPaymentCurrency: string | null; limits: InsuranceLimit[] | null; notes: string | null; status: string | null }

/**
 * Data for creating transaction
 */
export type InsertInvestmentTransaction = { investmentId: string | null; type: string; ticker: string; companyName: string; quantity: string; pricePerUnit: string; currency: string; transactionDate: number }

/**
 * Data for creating/updating loan
 */
export type InsertLoan = { name: string; principal: string; currency: string | null; interestRate: string | null; interestRateValidityDate: number | null; monthlyPayment: string | null; startDate: number | null; endDate: number | null; 
/**
 * Manual outstanding balance; must come with `balance_anchor_date`.
 * Both absent means "amortize from the principal at the start date".
 */
balanceAnchorAmount: string | null; balanceAnchorDate: number | null }

/**
 * Data for recording a loan event.
 */
export type InsertLoanEvent = { loanId: string; kind: string; eventDay: number; amount: string | null; rate: string | null; monthlyPayment: string | null; note: string | null }

/**
 * Data for creating/updating other asset
 */
export type InsertOtherAsset = { name: string; quantity: string | null; marketPrice: string | null; currency: string | null; averagePurchasePrice: string | null; yieldType: string | null; yieldValue: string | null }

/**
 * Data for creating transaction
 */
export type InsertOtherAssetTransaction = { assetId: string | null; type: string; quantity: string; pricePerUnit: string; currency: string; transactionDate: number }

/**
 * Data for creating/updating real estate
 */
export type InsertRealEstate = { name: string; address: string; type: string; purchasePrice: string | null; purchasePriceCurrency: string | null; marketPrice: string | null; marketPriceCurrency: string | null; monthlyRent: string | null; monthlyRentCurrency: string | null; recurringCosts: RecurringCost[] | null; photos: string[] | null; notes: string | null }

/**
 * Data for creating stock investment. Quantity and average price are not
 * accepted: they derive from the transaction record (pass an initial
 * transaction on create).
 */
export type InsertStockInvestment = { ticker: string; companyName: string }

/**
 * Data for creating a stock tag
 */
export type InsertStockTag = { name: string; color: string | null; groupId: string | null }

/**
 * Data for creating a stock tag group
 */
export type InsertStockTagGroup = { name: string; description: string | null }

/**
 * Data for creating a category
 */
export type InsertTransactionCategory = { name: string; icon: string | null; color: string | null; parentId: string | null; sortOrder: number | null }

/**
 * Data for creating/updating user profile
 */
export type InsertUserProfile = { name: string; surname: string; email: string; menuPreferences: MenuPreferences | null; currency: string | null; language: string | null; excludePersonalRealEstate: boolean | null }

/**
 * Insert payload for following a stock
 */
export type InsertWatchedStock = { ticker: string }

/**
 * Financial institution (bank)
 */
export type Institution = { id: string; name: string; bic: string | null; country: string | null; logoUrl: string | null; createdAt: number }

/**
 * Insurance document (attached contracts, certificates, etc.)
 */
export type InsuranceDocument = { id: string; insuranceId: string; name: string; description: string | null; filePath: string; fileType: string; fileSize: number | null; uploadedAt: number }

/**
 * Insurance limit
 */
export type InsuranceLimit = { title: string; amount: number; currency: string }

/**
 * Insurance policy
 */
export type InsurancePolicy = { id: string; type: string; provider: string; policyName: string; policyNumber: string | null; startDate: number; endDate: number | null; paymentFrequency: string; oneTimePayment: string | null; oneTimePaymentCurrency: string | null; regularPayment: string; regularPaymentCurrency: string; limits: InsuranceLimit[]; notes: string | null; status: string; createdAt: number; updatedAt: number }

/**
 * Result of `PRAGMA quick_check` (+ `cipher_integrity_check`).
 */
export type IntegrityReport = { ok: boolean; messages: string[] }

/**
 * Investment transaction (buy/sell)
 */
export type InvestmentTransaction = { id: string; investmentId: string; type: string; ticker: string; companyName: string; quantity: string; pricePerUnit: string; currency: string; transactionDate: number; createdAt: number }

/**
 * Loan
 */
export type Loan = { id: string; name: string; principal: string; currency: string; interestRate: string; interestRateValidityDate: number | null; monthlyPayment: string; startDate: number; endDate: number | null; 
/**
 * Real outstanding balance entered by the user (e.g. from a statement);
 * set together with `balance_anchor_date`, amortization continues from it.
 */
balanceAnchorAmount: string | null; 
/**
 * UTC day the manual balance applies to.
 */
balanceAnchorDate: number | null; 
/**
 * Read-only: amortized balance as of today's UTC day, in the loan's own
 * currency with 2 decimals (computed on every read, never stored).
 */
outstandingBalance: string; createdAt: number; updatedAt: number }

/**
 * One event in a loan's life. Money and rates are TEXT like everywhere else.
 */
export type LoanEvent = { id: string; loanId: string; 
/**
 * `extra_payment` | `rate_change` | `balance_check`.
 */
kind: string; 
/**
 * UTC day of the event (ADR 0008).
 */
eventDay: number; 
/**
 * Extra payment amount, or the balance confirmed by a statement.
 */
amount: string | null; 
/**
 * New annual rate in percent (`rate_change`).
 */
rate: string | null; 
/**
 * New regular payment (`rate_change`, or an `extra_payment` the bank used to lower it).
 */
monthlyPayment: string | null; note: string | null; createdAt: number }

/**
 * Repayment schedule and totals of one loan as of today (loan detail page).
 */
export type LoanSchedule = { loanId: string; 
/**
 * Valuation day (today, UTC).
 */
asOfDay: number; 
/**
 * Amount and day the amortization starts from.
 */
anchorAmount: string; anchorDay: number; 
/**
 * True when the anchor is the user's manual balance, false for
 * principal at the start date.
 */
anchorIsManual: boolean; outstandingBalance: string; 
/**
 * Anchor amount minus the balance as of `asOfDay` (negative when it grew).
 */
principalRepaid: string; 
/**
 * Interest included in the payments between the anchor and `asOfDay`.
 */
interestPaid: string; paymentsMade: number; 
/**
 * Payments left until the balance is 0; None when the schedule does not
 * reach 0 (no payment, payment below interest, ends at `end_date`).
 */
paymentsRemaining: number | null; payoffDay: number | null; rows: LoanScheduleRow[]; 
/**
 * Codes the UI translates: `noPayment`, `paymentBelowInterest`,
 * `balanceAtEndDate`, `scheduleTruncated`.
 */
warnings: string[] }

/**
 * One payment of a loan's repayment schedule (money as TEXT, 2 decimals).
 */
export type LoanScheduleRow = { 
/**
 * UTC day the payment falls due.
 */
dueDay: number; payment: string; interest: string; 
/**
 * Negative when the payment does not cover the interest.
 */
principalPart: string; balanceAfter: string }

export type McpServerStatus = { running: boolean; port: number; url: string; tokenSet: boolean; lastError: string | null }

/**
 * Menu preferences for sidebar visibility
 */
export type MenuPreferences = { loans: boolean; insurance: boolean; investments: boolean; bonds: boolean; realEstate: boolean; crypto?: boolean; otherAssets?: boolean }

/**
 * Done-state of the dashboard "Getting started" checklist plus the
 * onboarding flags stored in `app_config`.
 */
export type OnboardingProgress = { hasAccount: boolean; hasTransactions: boolean; hasInvestment: boolean; hasBudget: boolean; lastBackupAt: number | null; checklistDismissed: boolean; completedAt: number | null }

/**
 * Other asset (commodities, collectibles, etc.)
 */
export type OtherAsset = { id: string; name: string; quantity: string; marketPrice: string; currency: string; averagePurchasePrice: string; yieldType: string; yieldValue: string | null; createdAt: number; updatedAt: number }

/**
 * Transaction for other asset
 */
export type OtherAssetTransaction = { id: string; assetId: string; type: string; quantity: string; pricePerUnit: string; currency: string; transactionDate: number; createdAt: number }

/**
 * One pack rule, with its disabled flag from app_config
 */
export type PackRuleInfo = { id: string; name: string; ruleType: string; pattern: string; categoryId: string; priority: number; disabled: boolean }

/**
 * Current portfolio metrics
 */
export type PortfolioMetrics = { totalSavings: number; totalInvestments: number; totalCrypto: number; totalBonds: number; totalRealEstatePersonal: number; totalRealEstateInvestment: number; totalRealEstate: number; totalOtherAssets: number; totalLiabilities: number; totalAssets: number; netWorth: number; savingsByCurrency: Partial<{ [key in string]: number }>; investmentsByCurrency: Partial<{ [key in string]: number }>; cryptoByCurrency: Partial<{ [key in string]: number }>; bondsByCurrency: Partial<{ [key in string]: number }>; realEstateByCurrency: Partial<{ [key in string]: number }>; loansByCurrency: Partial<{ [key in string]: number }>; otherAssetsByCurrency: Partial<{ [key in string]: number }> }

/**
 * Portfolio metrics history entry
 */
export type PortfolioMetricsHistory = { id: string; totalSavings: string; totalLoansPrincipal: string; totalInvestments: string; totalCrypto: string; totalBonds: string; totalRealEstatePersonal: string; totalRealEstateInvestment: string; totalOtherAssets: string; recordedAt: number; investmentsByCurrency: string; cryptoByCurrency: string; savingsByCurrency: string; bondsByCurrency: string; realEstateByCurrency: string; loansByCurrency: string; otherAssetsByCurrency: string; 
/**
 * `"live"` (recorded by the running app) or `"backfill"` (reconstructed;
 * the static classes of such a day are carried from the nearest live row).
 */
source: string }

/**
 * Status of prices and exchange rates freshness
 */
export type PriceStatus = { 
/**
 * Are any stock prices considered stale (older than 24 hours)?
 */
stocksStale: boolean; 
/**
 * Are any crypto prices considered stale (older than 12 hours)?
 */
cryptoStale: boolean; 
/**
 * Are exchange rates considered stale (older than 48 hours)?
 */
exchangeRatesStale: boolean; 
/**
 * Age of oldest stock price in hours (None if no stocks)
 */
oldestStockPriceAgeHours: number | null; 
/**
 * Age of oldest crypto price in hours (None if no crypto)
 */
oldestCryptoPriceAgeHours: number | null; 
/**
 * Age of exchange rates in hours (None if never fetched)
 */
exchangeRatesAgeHours: number | null; 
/**
 * Number of stocks without any price data
 */
stocksMissingPrice: number; 
/**
 * Number of cryptos without any price data
 */
cryptoMissingPrice: number; 
/**
 * Currency codes encountered this session with no known exchange rate
 * (converted 1:1 to CZK as a last resort — values are wrong; audit M2)
 */
missingCurrencies: string[] }

/**
 * Projection settings for a specific asset type
 */
export type ProjectionSettings = { id: string; assetType: string; 
/**
 * Yearly growth in percent as text. An explicit `"0"` is honoured as 0 %.
 * An empty string means "not set": savings and bonds then use the weighted
 * rate calculated from the user's own accounts / bonds, the other classes
 * their built-in default.
 */
yearlyGrowthRate: string; 
/**
 * Monthly contribution in CZK (the base currency, ADR 0001) as text.
 */
monthlyContribution: string; contributionCurrency: string; enabled: boolean; createdAt?: number; updatedAt?: number }

/**
 * Real estate property
 */
export type RealEstate = { id: string; name: string; address: string; type: string; purchasePrice: string; purchasePriceCurrency: string; marketPrice: string; marketPriceCurrency: string; monthlyRent: string | null; monthlyRentCurrency: string | null; recurringCosts: RecurringCost[]; photos: string[]; notes: string | null; createdAt: number; updatedAt: number }

/**
 * Real estate document (attached contracts, deeds, etc.)
 */
export type RealEstateDocument = { id: string; realEstateId: string; name: string; description: string | null; filePath: string; fileType: string; fileSize: number | null; uploadedAt: number }

/**
 * One-time cost for real estate
 */
export type RealEstateOneTimeCost = { id: string; realEstateId: string; name: string; description: string | null; amount: string; currency: string; date: number; createdAt: number }

/**
 * Individual photo within a batch
 */
export type RealEstatePhoto = { id: string; batchId: string; filePath: string; thumbnailPath: string; createdAt: number }

/**
 * Photo batch (groups photos by date and description)
 */
export type RealEstatePhotoBatch = { id: string; realEstateId: string; photoDate: number; description: string | null; photos: RealEstatePhoto[]; createdAt: number }

/**
 * Where a ticker's rebuild stands.
 */
export type RecalcStatus = "running" | "done" | "failed"

/**
 * Recurring cost for real estate
 */
export type RecurringCost = { name: string; amount: number; frequency: string; currency: string | null }

/**
 * How often one rule matched in the period (TS `RuleHitCount`).
 */
export type RuleHitCount = { 
/**
 * Custom rule id, pack rule id, or the learned payee's id.
 */
ruleId: string; hits: number; 
/**
 * Booking day of the newest matching transaction.
 */
lastHit: number | null }

/**
 * What a draft rule would match today (TS `RuleMatchPreview`).
 */
export type RuleMatchPreview = { matches: number; 
/**
 * Matching transactions that have no category today.
 */
uncategorized: number; 
/**
 * The newest matches, at most five.
 */
samples: RuleMatchSample[] }

/**
 * One transaction a draft rule matches (TS `RuleMatchSample`).
 */
export type RuleMatchSample = { bookingDate: number; description: string | null; counterparty: string | null; 
/**
 * Signed decimal string (debits negative).
 */
amount: string; currency: string; categoryId: string | null }

/**
 * One shipped rule pack, with its enabled flag from app_config
 */
export type RulePackInfo = { packId: string; country: string; version: number; ruleCount: number; enabled: boolean }

/**
 * Interest rate zone (tier) of a bank account
 */
export type SavingsAccountZone = { id: string; savingsAccountId: string; fromAmount: string; toAmount: string | null; interestRate: string; createdAt: number }

export type SourceCount = { 
/**
 * `rule`, `exact_match`, `own_account`, `mcp`, `manual` (a category without a recorded source).
 */
source: string; count: number }

/**
 * Stock investment holding
 */
export type StockInvestment = { id: string; ticker: string; companyName: string; quantity: string; averagePrice: string; 
/**
 * Currency of the average price (determined by first transaction)
 */
averagePriceCurrency: string }

/**
 * Detail for any ticker — works for un-followed tickers too (followed=false,
 * notes empty, target None). All stock_data fields are None when the cache
 * has no row yet (e.g. offline right after a search).
 */
export type StockMonitorDetail = { ticker: string; followed: boolean; targetPrice: string | null; notes: string; shortName: string | null; longName: string | null; currency: string | null; currentPrice: string | null; previousClose: string | null; fiftyTwoWeekLow: string | null; fiftyTwoWeekHigh: string | null; marketCap: string | null; peRatio: string | null; 
/**
 * Raw Yahoo fraction (0.0044 = 0.44 %); multiply by 100 for display.
 */
trailingDividendYield: string | null; exchange: string | null; priceFetchedAt: number | null; heldInvestmentId: string | null; isHeld: boolean; 
/**
 * When the stock was added to the watchlist (unix seconds); None when not followed.
 */
followedAt: number | null }

/**
 * User price override
 */
export type StockPriceOverride = { id: string; ticker: string; price: string; currency: string; updatedAt: number }

/**
 * Chart data point (transient, never persisted — f64 like HistoricalPrice)
 */
export type StockPricePoint = { timestamp: number; price: number; currency: string }

/**
 * Stock tag for categorizing investments (e.g., Growth, Value, Dividend)
 */
export type StockTag = { id: string; name: string; color: string | null; groupId: string | null; createdAt: number }

/**
 * Stock tag group for organizing related tags
 */
export type StockTagGroup = { id: string; name: string; description: string | null; createdAt: number }

/**
 * Per-ticker value history record
 */
export type TickerValueHistory = { ticker: string; recordedAt: number; valueCzk: string; quantity: string; price: string; currency: string }

/**
 * Transaction category
 */
export type TransactionCategory = { id: string; name: string; icon: string | null; color: string | null; parentId: string | null; sortOrder: number; isSystem: boolean; createdAt: number }

/**
 * Filters for querying transactions
 */
export type TransactionFilters = { dateFrom: number | null; dateTo: number | null; categoryId: string | null; txType: string | null; search: string | null; limit: number | null; offset: number | null }

/**
 * Result of transaction query with pagination
 */
export type TransactionQueryResult = { transactions: BankTransaction[]; total: number }

/**
 * Transaction status
 */
export type TransactionStatus = "booked" | "pending"

/**
 * Transaction type
 */
export type TransactionType = "credit" | "debit"

/**
 * A single data point in a TWR time series.
 */
export type TwrDataPoint = { 
/**
 * Calendar date as "YYYY-MM-DD"
 */
date: string; 
/**
 * Cumulative time-weighted return in percent (0.0 at start of range)
 */
twr: number }

/**
 * A complete TWR series for one tag, untagged stocks, or the whole portfolio.
 */
export type TwrSeries = { 
/**
 * The tag this series belongs to. None = whole portfolio or untagged.
 */
tag: StockTag | null; 
/**
 * True when this series represents stocks with no tags assigned.
 */
isUntagged: boolean; data: TwrDataPoint[] }

/**
 * Data for editing a category's definition. A field that is absent (`None`)
 * is left unchanged, so an edit dialog can send only what the user touched.
 */
export type UpdateTransactionCategory = { name: string | null; icon: string | null; color: string | null }

/**
 * Data for updating user profile (partial updates)
 */
export type UpdateUserProfile = { name: string | null; surname: string | null; email: string | null; menuPreferences: MenuPreferences | null; currency: string | null; language: string | null; excludePersonalRealEstate: boolean | null; coingeckoModalDismissed: boolean | null; mcpServerEnabled: boolean | null }

/**
 * User profile stored in database
 */
export type UserProfile = { id: number; name: string; surname: string; email: string; menuPreferences: MenuPreferences; currency: string; language: string; excludePersonalRealEstate: boolean; coingeckoModalDismissed?: boolean; mcpServerEnabled?: boolean; createdAt: number }

/**
 * A followed stock (row in watched_stocks)
 */
export type WatchedStock = { id: string; ticker: string; targetPrice: string | null; notes: string; createdAt: number; updatedAt: number }

/**
 * Overview-table row: watchlist entry enriched from the stock_data cache
 */
export type WatchedStockRow = { id: string; ticker: string; targetPrice: string | null; notes: string; shortName: string | null; longName: string | null; currency: string | null; currentPrice: string | null; previousClose: string | null; fiftyTwoWeekLow: string | null; fiftyTwoWeekHigh: string | null; exchange: string | null; priceFetchedAt: number | null; heldInvestmentId: string | null; isHeld: boolean; 
/**
 * When the stock was added to the watchlist (unix seconds).
 */
followedAt: number }

